#!/bin/bash

# exit script if return code != 0
set -e

# redirect new file descriptors and then tee stdout & stderr to supervisor log and console (captures output from this script)
exec 3>&1 4>&2 &> >(tee -a /config/supervisord.log)

# The system Wine (10.x staging, shipped by the upstream image) is used as-is:
# it runs the GIANTS retail build correctly once installed from the official
# *_ESD.img installer.

# source in utilities script
source 'utils.sh'

cat << "EOF"
Created by...
___.   .__       .__
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    <
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

EOF

# source in environment variables containing information about the build
# this file is generated by the build script and contains the app name and release tag
source '/etc/image-build-info'

if [[ "${HOST_OS,,}" == "unraid" ]]; then
	echo "[info] Host is running unRAID" | ts '%Y-%m-%d %H:%M:%.S'
fi

echo "[info] System information: $(uname -a)" | ts '%Y-%m-%d %H:%M:%.S'

echo "[info] Image architecture: '${TARGETARCH}'" | ts '%Y-%m-%d %H:%M:%.S'

echo "[info] Application name: '${APPNAME}'" | ts '%Y-%m-%d %H:%M:%.S'

echo "[info] Base image release tag: '${BASE_RELEASE_TAG}'" | ts '%Y-%m-%d %H:%M:%.S'

echo "[info] Application image release tag: '${IMAGE_RELEASE_TAG}'" | ts '%Y-%m-%d %H:%M:%.S'

# NOTE Do not move PUID/PGID below PLACEHOLDERS, as they are referenced
export PUID=$(echo "${PUID}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${PUID}" ]]; then
	echo "[info] PUID defined as '${PUID}'" | ts '%Y-%m-%d %H:%M:%.S'
else
	echo "[warn] PUID not defined (via -e PUID), defaulting to '99'" | ts '%Y-%m-%d %H:%M:%.S'
	export PUID="99"
fi

# set user nobody to specified user id (non unique)
: # usermod skipped (already uid 1000)

export PGID=$(echo "${PGID}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${PGID}" ]]; then
	echo "[info] PGID defined as '${PGID}'" | ts '%Y-%m-%d %H:%M:%.S'
else
	echo "[warn] PGID not defined (via -e PGID), defaulting to '100'" | ts '%Y-%m-%d %H:%M:%.S'
	export PGID="100"
fi

# set group users to specified group id (non unique)
: # groupmod skipped (already gid 1000)

# set umask to specified value if defined
if [[ ! -z "${UMASK}" ]]; then
	echo "[info] UMASK defined as '${UMASK}'" | ts '%Y-%m-%d %H:%M:%.S'
	# umask pre-applied at build time
else
	echo "[warn] UMASK not defined (via -e UMASK), defaulting to '000'" | ts '%Y-%m-%d %H:%M:%.S'
	# umask pre-applied at build time
fi

# check for presence of perms file, if it exists then skip setting
# permissions, otherwise recursively set on /config for host
if [[ ! -f "/config/perms.txt" ]]; then

	if [[ -d "/config" ]]; then

		echo "[info] Setting ownership and permissions recursively on '/config'..." | ts '%Y-%m-%d %H:%M:%.S'

		set +e
		chown -R "${PUID}":"${PGID}" "/config"
		exit_code_chown=$?
		chmod -R 775 "/config"
		exit_code_chmod=$?
		set -e

		if (( exit_code_chown != 0 || exit_code_chmod != 0 )); then
			echo "[warn] Unable to chown/chmod '/config', assuming SMB mountpoint" | ts '%Y-%m-%d %H:%M:%.S'
		else
			echo "[info] Successfully set ownership and permissions on '/config'" | ts '%Y-%m-%d %H:%M:%.S'
		fi

	else

		echo "[fatal] '/config' directory does not exist, exiting script..." | ts '%Y-%m-%d %H:%M:%.S'
		exit 1

	fi

	if [[ -d "/data" ]]; then

		echo "[info] Setting ownership and permissions non-recursively on '/data'..." | ts '%Y-%m-%d %H:%M:%.S'

		set +e
		chown "${PUID}":"${PGID}" "/data"
		exit_code_chown=$?
		chmod 775 "/data"
		exit_code_chmod=$?
		set -e

		if (( exit_code_chown != 0 || exit_code_chmod != 0 )); then
			echo "[info] Unable to chown/chmod '/data', assuming SMB mountpoint" | ts '%Y-%m-%d %H:%M:%.S'
		else
			echo "[info] Successfully set ownership and permissions on '/data'" | ts '%Y-%m-%d %H:%M:%.S'
		fi

	else

		echo "[info] '/data' directory does not exist, skipping setting (non-recursive) ownership and permissions on '/data'" | ts '%Y-%m-%d %H:%M:%.S'

	fi

	echo "This file prevents ownership and permissions from being applied/re-applied to '/config' and '/data', if you want to reset ownership and permissions then please delete this file and restart the container." > /config/perms.txt

else

	echo "[info] Permissions file '/config/perms.txt' exists, skipping setting ownership and permissions on '/config' and '/data'" | ts '%Y-%m-%d %H:%M:%.S'

fi

# calculate disk usage for /tmp in bytes
disk_usage_tmp=$(du -s /tmp | awk '{print $1}')

# if disk usage of /tmp exceeds 1GB then do not clear down (could possibly be volume mount to media)
if [ "${disk_usage_tmp}" -gt 1073741824 ]; then

	echo "[warn] /tmp directory contains 1GB+ of data, skipping clear down as this maybe mounted media" | ts '%Y-%m-%d %H:%M:%.S'
	echo "[info] Showing contents of /tmp..." | ts '%Y-%m-%d %H:%M:%.S'
	ls -al /tmp

else

	echo "[info] Deleting files in /tmp (non recursive)..." | ts '%Y-%m-%d %H:%M:%.S'
	rm -f /tmp/* > /dev/null 2>&1 || true
	rm -rf /tmp/tmux*

fi

# ENVVARS_COMMON_PLACEHOLDER


export WEBPAGE_TITLE=$(echo "${WEBPAGE_TITLE}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${WEBPAGE_TITLE}" ]]; then
	echo "[info] WEBPAGE_TITLE defined as '${WEBPAGE_TITLE}'" | ts '%Y-%m-%d %H:%M:%.S'
fi

export VNC_PASSWORD=$(echo "${VNC_PASSWORD}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${VNC_PASSWORD}" ]]; then
	echo "[info] VNC_PASSWORD defined as '${VNC_PASSWORD}'" | ts '%Y-%m-%d %H:%M:%.S'
fi

export HTTPS_CERT_PATH=$(echo "${HTTPS_CERT_PATH}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${HTTPS_CERT_PATH}" ]]; then
	echo "[info] HTTPS_CERT_PATH defined as '${HTTPS_CERT_PATH}'" | ts '%Y-%m-%d %H:%M:%.S'
fi

export HTTPS_KEY_PATH=$(echo "${HTTPS_KEY_PATH}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${HTTPS_KEY_PATH}" ]]; then
	echo "[info] HTTPS_KEY_PATH defined as '${HTTPS_KEY_PATH}'" | ts '%Y-%m-%d %H:%M:%.S'
fi

export ENABLE_STARTUP_SCRIPTS=$(echo "${ENABLE_STARTUP_SCRIPTS}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${ENABLE_STARTUP_SCRIPTS}" ]]; then
	echo "[info] ENABLE_STARTUP_SCRIPTS defined as '${ENABLE_STARTUP_SCRIPTS}'" | ts '%Y-%m-%d %H:%M:%.S'
else
	echo "[info] ENABLE_STARTUP_SCRIPTS not defined,(via -e ENABLE_STARTUP_SCRIPTS), defaulting to 'no'" | ts '%Y-%m-%d %H:%M:%.S'
	export ENABLE_STARTUP_SCRIPTS="no"
fi



# Copy writable templates for runtime config edits (container fs is read-only under Pelican)
mkdir -p /home/container/.fs25-build
cp /usr/local/share/fs25-templates/* /home/container/.fs25-build/

# Webserver

if [ -n "$WEB_USERNAME" ]; then
    sed -i "s/<username>admin<\/username>/<username>$WEB_USERNAME<\/username>/" /home/container/.fs25-build/default_dedicatedServer.xml
fi

if [ -n "$WEB_PASSWORD" ]; then
    sed -i "s/<passphrase>webpassword<\/passphrase>/<passphrase>$WEB_PASSWORD<\/passphrase>/" /home/container/.fs25-build/default_dedicatedServer.xml
fi

# Gameserver

if [ -n "$SERVER_NAME" ]; then
    sed -i "s/<game_name><\/game_name>/<game_name>$SERVER_NAME<\/game_name>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_ADMIN" ]; then
    sed -i "s/<admin_password><\/admin_password>/<admin_password>$SERVER_ADMIN<\/admin_password>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_PASSWORD" ]; then
    sed -i "s/<game_password><\/game_password>/<game_password>$SERVER_PASSWORD<\/game_password>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_PLAYERS" ]; then
    sed -i "s/<max_player>12<\/max_player>/<max_player>$SERVER_PLAYERS<\/max_player>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_PORT" ]; then
    sed -i "s/<port>10823<\/port>/<port>$SERVER_PORT<\/port>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_REGION" ]; then
    sed -i "s/<language>en<\/language>/<language>$SERVER_REGION<\/language>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_MAP" ]; then
    sed -i "s/<mapID>MapUS<\/mapID>/<mapID>$SERVER_MAP<\/mapID>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_DIFFICULTY" ]; then
    sed -i "s/<difficulty>3<\/difficulty>/<difficulty>$SERVER_DIFFICULTY<\/difficulty>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_PAUSE" ]; then
    sed -i "s/<pause_game_if_empty>2<\/pause_game_if_empty>/<pause_game_if_empty>$SERVER_PAUSE<\/pause_game_if_empty>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_SAVE_INTERVAL" ]; then
    sed -i "s/<auto_save_interval>180.000000<\/auto_save_interval>/<auto_save_interval>$SERVER_SAVE_INTERVAL<\/auto_save_interval>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_STATS_INTERVAL" ]; then
    sed -i "s/<stats_interval>360.000000<\/stats_interval>/<stats_interval>$SERVER_STATS_INTERVAL<\/stats_interval>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

if [ -n "$SERVER_CROSSPLAY" ]; then
    sed -i "s/<crossplay_allowed>true<\/crossplay_allowed>/<crossplay_allowed>$SERVER_CROSSPLAY<\/crossplay_allowed>/" /home/container/.fs25-build/default_dedicatedServerConfig.xml
fi

export APPLICATION="fs25server"




# get previous puid/pgid (if first run then will be empty string)
previous_puid=$(cat "/home/container/.puid" 2>/dev/null || true)
previous_pgid=$(cat "/home/container/.pgid" 2>/dev/null || true)

# if first run (no puid or pgid files in /tmp) or the PUID or PGID env vars are different
# from the previous run then re-apply chown with current PUID and PGID values.
if [[ ! -f "/home/container/.puid" || ! -f "/home/container/.pgid" || "${previous_puid}" != "${PUID}" || "${previous_pgid}" != "${PGID}" ]]; then

	# set permissions inside container - Do NOT double quote variable for install_paths otherwise this will wrap space separated paths as a single string
	: # chown /home/nobody skipped

fi

# write out current PUID and PGID to files in /root (used to compare on next run)
echo "${PUID}" > /home/container/.puid
echo "${PGID}" > /home/container/.pgid




if [[ "${ENABLE_STARTUP_SCRIPTS}" == "yes" ]]; then

	# define path to scripts
	base_path="/config/home"
  user_script_src_path="/home/nobody/.build/scripts/example-startup-script.sh"
	user_script_dst_path="${base_path}/scripts"

	mkdir -p "${user_script_dst_path}"

	# copy example startup script
	# note slence stdout/stderr and ensure exit code 0 due to src file may not exist (symlink)
	if [[ ! -f "${user_script_dst_path}/example-startup-script.sh" ]]; then
		cp "${user_script_src_path}" "${user_script_dst_path}/example-startup-script.sh" 2> /dev/null || true
	fi

	# find any scripts located in "${user_script_dst_path}"
	user_scripts=$(find "${user_script_dst_path}" -maxdepth 1 -name '*sh' 2> '/dev/null' | xargs)

	# loop over scripts, make executable and source
	for i in ${user_scripts}; do
		chmod +x "${i}"
		echo "[info] Executing user script '${i}' in the background" | ts '%Y-%m-%d %H:%M:%.S'
		source "${i}" &
	done

	# change ownership as we are running as root
	chown -R nobody:users "${base_path}"

fi

# call symlink function from utils.sh
# Use the resolved path because /config is itself a symlink to /home/container.
symlink --src-path '/home/container/home' --dst-path '/home/nobody' --link-type 'softlink'


# set permissions to allow rw for all users (used when appending util output to supervisor log)
chmod 666 "/config/supervisord.log"

# If installer files were uploaded to /opt/fs25/installer, run the silent GIANTS
# installer in the background once X and the Wine prefix are up.
nohup /usr/local/bin/install_fs25.sh >/dev/null 2>&1 &

# If a GIANTS license key is present (file or GIANTS_LICENSE_KEY env), run the
# headless activation helper in the background. It waits for the X server and
# the activation window, then types the key automatically.
if [ -f "/home/container/.fs25_key" ] || [ -n "${GIANTS_LICENSE_KEY:-}" ]; then
	echo "[info] Found FS25 license key, starting headless activation helper" | ts '%Y-%m-%d %H:%M:%.S'
	nohup /usr/local/bin/activate_fs25.sh >/home/container/activation.log 2>&1 &
fi

echo "[info] Starting Supervisor..." | ts '%Y-%m-%d %H:%M:%.S'

# restore file descriptors to prevent duplicate stdout & stderr to supervisord.log
exec 1>&3 2>&4

exec /usr/bin/supervisord -c /etc/supervisord.conf -n
